<!doctype html>
<html>
  <head>
    <meta charset='UTF-8'>
    <script src='assets/js/heart.js'></script>
    <meta name='viewport' content='width=device-width initial-scale=1'>
    <link href='https://fonts.loli.net/css?family=Open+Sans:400italic,700italic,700,400&subset=latin,latin-ext' rel='stylesheet' type='text/css' />
    <link href='assets/css/typora.css' rel="stylesheet">
    <title>QiuSYan's API</title>
  </head>
  <body class='typora-export os-windows'>
    <?php echo '<div id=\'write\' class=\'\'><h1><a name="qiusyans-api" class="md-header-anchor"></a><span>QiuSYan&#39;s API</span></h1><p><strong><span>目前可用API有：</span></strong></p><ul><li><p><a href=\'yiyan.php\'><span>随机一言</span></a></p><ul><li><p><span>效果展示：</span></p><blockquote><p><span><script src="https://api.qiusyan.top/yiyan.php"></script></span></p></blockquote></li><li><p><span>调用方式：</span></p><blockquote><p><span>在您的HTML页面需要调用处插入：</span></p><pre spellcheck="false" class="md-fences md-end-block ty-contain-cm modeLoaded md-focus" lang="html"><div class="CodeMirror cm-s-inner CodeMirror-wrap" lang="html"><div style="overflow: hidden; position: relative; width: 3px; height: 0px; top: 0px; left: 502.281px;"><textarea autocorrect="off" autocapitalize="off" spellcheck="false" tabindex="0" style="position: absolute; bottom: -1em; padding: 0px; width: 1000px; height: 1em; outline: none;"></textarea></div><div class="CodeMirror-scrollbar-filler" cm-not-content="true"></div><div class="CodeMirror-gutter-filler" cm-not-content="true"></div><div class="CodeMirror-scroll" tabindex="-1"><div class="CodeMirror-sizer" style="margin-left: 0px; margin-bottom: 0px; border-right-width: 0px; padding-right: 0px; padding-bottom: 0px;"><div style="position: relative; top: 0px;"><div class="CodeMirror-lines" role="presentation"><div role="presentation" style="position: relative; outline: none;"><div class="CodeMirror-measure"></div><div class="CodeMirror-measure"></div><div style="position: relative; z-index: 1;"></div><div class="CodeMirror-code" role="presentation"><div class="CodeMirror-activeline" style="position: relative;"><div class="CodeMirror-activeline-background CodeMirror-linebackground"></div><div class="CodeMirror-gutter-background CodeMirror-activeline-gutter" style="left: 0px; width: 0px;"></div><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-tag cm-bracket">&lt;</span><span class="cm-tag">script</span> <span class="cm-attribute">src</span>=<span class="cm-string">"https://api.qiusyan.top/yiyan.php"</span><span class="cm-tag cm-bracket">&gt;&lt;/</span><span class="cm-tag">script</span><span class="cm-tag cm-bracket">&gt;</span></span></pre></div></div></div></div></div></div><div style="position: absolute; height: 0px; width: 1px; border-bottom: 0px solid transparent; top: 23px;"></div><div class="CodeMirror-gutters" style="display: none; height: 23px;"></div></div></div></pre></blockquote></li></ul></li></ul></div>'; ?>
  </body>
</html>
